server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order-management
    username: admin
    password: admin
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

